version: '3'
services:
  ubuntu:
    image: k8s-ubuntu
    build:
      context: ./
      dockerfile: Dockerfile.ubuntu18
    container_name: k8s-ubuntu
    hostname: k8s-ubuntu
    volumes:
      - ./ubuntu/cron.d:/etc/cron.d
      - ./ubuntu/data:/data
      - ./ubuntu/home:/root
    ports:
      - '1022:22'
